meta:
  config_version: 3
  client_id: local
  database_name: ursa
  euid_client_code: R
  # Explicit env contract for TapDB/Meridian subprocesses:
  # MERIDIAN_DOMAIN_CODE=R
  # TAPDB_APP_CODE=R
environments:
  dev:
    engine_type: local
    host: localhost
    port: '5588'
    ui_port: '8918'
    database: tapdb_ursa_dev
    audit_log_euid_prefix: RGX
    support_email: support@lsmc.bio
    cognito_user_pool_id: ''
  prod:
    engine_type: aurora
    host: ursa.cluster-REPLACE.us-west-2.rds.amazonaws.com
    port: '5432'
    user: tapdb_admin
    password: ''
    database: tapdb_ursa_prod
    audit_log_euid_prefix: RGX
    support_email: support@lsmc.bio
    cognito_user_pool_id: ''
    region: us-west-2
    cluster_identifier: ursa
    iam_auth: 'true'
    ssl: 'true'
